### ISSUE TITLE
Node-gyp compile error

### ISSUE THREAD

**Issue by tmcdonnell87** [ddopson/node-segfault-handler#21] opened 2015-01-29 22:32 UTC
Windows 7 machine, compiling with VS2013 express for Desktop. 
node -v v0.10.32
npm -v 1.4.28

Node-gyp compiles fine for other modules (e.g. libxmljs), but fails here. 

C:\Users\mcdonnel\Documents\validator\node_modules\segfault-handler>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  segfault-handler.cpp
..\src\segfault-handler.cpp(2): fatal error C1083: Cannot open include file: 'execinfo.h': No such file or directory [C:\Users\mcdonnel\Documents\validator\node_modules\segfault-handler\build\segfault-handler.vcxproj]
gyp
npm ERR! segfault-handler@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the segfault-handler@0.2.4 install script.
npm ERR! This is most likely a problem with the segfault-handler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls segfault-handler
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "nan@1.5.1" "segfault-handler"
npm ERR! cwd C:\Users\mcdonnel\Documents\validator
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE

Any suggestions would be appreciated. Thanks!

**Comment by No9** [comment] 2015-01-30 09:29
Hi @tmcdonnell87  
 segfault-handler doesn't support Windows at the moment as compatibility is not trivial. 

@ddopson have you looked into this at all?

**Comment by ddopson** [comment] 2015-01-30 17:18
Yeah, it would require some work to find the right API's and build an implementation.  I'd encourage someone to do it, but I can't as I lack access to a win32 machine to test on.

**Comment by tmcdonnell87** [comment] 2015-01-30 17:49
Unfortunately not my area of expertise, but I'd love to use it if/when someone is able to tackle it. 

In the short term, I'd suggest updating the Readme with the systems that are supported.

Thanks for the prompt responses!

**Comment by No9** [comment] 2015-01-30 21:15
Agreed we are also facing issues with FreeBSD 
https://github.com/ddopson/node-segfault-handler/issues/22

**Comment by No9** [comment] 2015-09-24 23:55
FYI @tmcdonnell87 so this will land soon https://github.com/ddopson/node-segfault-handler/pull/31 
And there will be windows support

**Comment by No9** [comment] 2015-12-02 01:58
@tmcdonnell87  So #31 landed I am closing this.
Please open another issue if you hit another issue and thanks for reporting

**Closed by No9** 2015-12-02 01:58 UTC

**Comment by c2xbrhdj6u4qs15** [comment] 2016-02-02 10:45
I get the same error on Windows 7 like tmcdonnell87 - see below

C:\cygwin64\home\U8009801\aggregator\node_modules\segfault-handler>node "C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  segfault-handler.cpp
..\src\segfault-handler.cpp(2): fatal error C1083: Cannot open include file: 'execinfo.h': No such file or directory [C:\cygwin64\home\U8009801\aggregator\node_modules\segfault-handler\build\segfault-handler.vcxproj]
npm ERR! segfault-handler@0.2.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the segfault-handler@0.2.4 install script.
npm ERR! This is most likely a problem with the segfault-handler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls segfault-handler
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\cygwin64\home\U8009801\aggregator
npm ERR! node -v v0.10.41
npm ERR! npm -v 1.4.29
npm ERR! code ELIFECYCLE

What could be the root cause of the issue? Thanks
